# Generated by Django 4.2.2 on 2024-09-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ocid", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("level", models.IntegerField()),
                ("class_name", models.CharField(max_length=255)),
                ("world_name", models.CharField(max_length=255)),
                ("STR", models.FloatField(default=0)),
                ("DEX", models.FloatField(default=0)),
                ("INT", models.FloatField(default=0)),
                ("LUK", models.FloatField(default=0)),
                ("최소_공격력", models.FloatField(default=0)),
                ("최대_공격력", models.FloatField(default=0)),
                ("데미지", models.FloatField(default=0)),
                ("보스_몬스터_데미지", models.FloatField(default=0)),
                ("방어율_무시", models.FloatField(default=0)),
                ("크리티컬_확률", models.FloatField(default=0)),
                ("크리티컬_데미지", models.FloatField(default=0)),
            ],
        ),
    ]
