# Generated by Django 5.1.4 on 2025-01-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_info", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_name", models.CharField(max_length=255, unique=True)),
                ("data", models.TextField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Character",
        ),
    ]
